---
Name: workflowconfig
After:
  - 'framework/*'
  - 'cms/*'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Symbiote\AdvancedWorkflow\Extensions\WorkflowApplicable
SilverStripe\CMS\Controllers\CMSPageEditController:
  extensions:
    - Symbiote\AdvancedWorkflow\Extensions\AdvancedWorkflowExtension
SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - Symbiote\AdvancedWorkflow\Extensions\AdvancedWorkflowExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - advancedworkflow/css/AdvancedWorkflowAdmin.css
---
Name: workflow_jobs
Only:
  moduleexists: queuedjobs
---
SilverStripe\Core\Injector\Injector:
  Symbiote\AdvancedWorkflow\Jobs\WorkflowReminderJob:
    properties:
      queuedJobService: %$Symbiote\QueuedJobs\Services\QueuedJobService
